Iter9
al-kirpichenko/shortlinks pull request #10
Opened 2023-05-19 08:49 UTC by al-kirpichenko

2023-05-19 21:58 UTC, maxlyaptsev requested changes

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/routes/routes.go
> +func GetRouter(app *app.App) http.Handler {
Гетеры и сетеры в go не используются
```suggestion
func Router(app *app.App) http.Handler {
```

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/app/apishort.go
> +	if err = json.Unmarshal(buf.Bytes(), &req); err != nil {
т.к. bytes.Buffer и r.Body реализуют интерфейс io.Reader,  можно не использовать буфер и читать напрямую из body (используя Decoder). А сейчас происходит лишнее чтение в буфер.

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/fs/fs.go
> +package fs
по такому названию сложно будет понять за что отвечает пакет
нужно всегда помнить что код будут читать другие разработчики, могут и не расшифровать)

Еще предложение - можно перенести эту структуру в пакет storage - название подходящее, функционал схожий, только место хранения отличается. Но пользователь, работаеющий с пакетом сможет выбрать нужный конструктор - `NewFileSstorage` или `NewInmemoryStorage`

2023-05-19 21:58 UTC, maxlyaptsev commented on config/config.go
>  type AppConfig struct {
конфигурация сейчас лежит на самом верхнем уровне, лучше ее убрать либо в cmd/shortener т.к. она относится именно к этому приложению либо в internal/config где лежит основной код

2023-05-19 21:58 UTC, maxlyaptsev commented on config/config.go
> +	if file := os.Getenv("FILE_STORAGE_PATH"); file != "" {
а если бы использовался сторонний пакет для енвов, достаточно было бы только одну строчку в структуру добавить

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/fs/fs.go
> +func (fs Fstorage) SaveToFile(fileName string) error {
в одной структуре не должны быть разные ресиверы (по значению и указателю)
кроме того, если это модель, странно иметь у нее метод сохранения в файл, это другая ответственность и должна быть другая сущность

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/fs/fs.go
> +func (fs *Fstorage) AddURL(short string, original string) {
метод называется безобидно, `AddURL`, а по факту происходит очень неожиданное мутирование структуры по ссылке, что может вызвать огромное количество проблем и трудноотлавливаемых плавающих багов

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/fs/fs.go
> +type Fstorage struct {
судя по полям структуры это не сторедж а модель, название вводит в заблуждение. Либо функционал подразумевался другой
Если это модель, то у нее экспортируемые поля, и AddURL не нужен.

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/fs/fs.go
> +func LoadInFile(fileName string) map[string]string {
название не соответствует логике функции

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/fs/fs.go
> +			panic(err)
эту панику потом будет сложно отловить, кроме того на панике упадет все приложения. Ошибки нужно возвращать явно

2023-05-19 21:58 UTC, maxlyaptsev commented on tmp/short-url-db.json
> +{"short_url":"9g2FXaHY","original_url":"https://pr24.yandex.ru"}
временные файлы не стоит держать в репозитории

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/middleware/logger.go
> +		logger, err := zap.NewDevelopment()
создание логера при каждом запросе это лишнее - лучше использовать глобальный заповский логер либо создать свой пакет с логером

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/middleware/logger.go
> +			panic(err)
паника завершит приложение (если не обрабатывается). В любом случае отследить причину будет сложно. Паники нигде не используем кроме инициализации приложения

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/middleware/logger.go
> +		duration := time.Since(start)
микрооптимизация: лишняя переменная не нужна, можно сразу в лог писать

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/middleware/logger.go
> +			status: 0,
не имеет смысла, у нас есть zero value

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/middleware/logger.go
> +		sugar := *logger.Sugar()
нет смысла создавать эту переменную, она используется один раз

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/app/apishort_test.go
> +	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ExitOnError)
не совсем понял для чего это здесь нужно. Тесты должны работать изолировано и никакие флаги не должны влиять. Только то что явно задали в конструкторах структур

2023-05-19 21:58 UTC, maxlyaptsev commented on internal/app/apishort_test.go
> +func Test_APIGetShortURL(t *testing.T) {
нужно использовать test tables - это общепринятый стандарт в go, каждый кейс выполняется изоливано и легко добавлять новые

2023-05-22 11:57 UTC, al-kirpichenko commented on internal/app/apishort_test.go
> +	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ExitOnError)
без него тесты падают с ошибкой flag redefined

2023-05-22 14:34 UTC, maxlyaptsev requested changes

2023-05-22 14:34 UTC, maxlyaptsev commented on internal/app/apishort.go
> +	a.Fstorage.Short = id
что если в тот же момент придет еще один запрос на получение короткой сссылки? Какое значение здесь будет?

2023-05-22 14:34 UTC, maxlyaptsev commented on internal/app/apishort.go
> +		log.Fatal(err)
Правильно ли здесь завершать приложение? Является ли эта ошибка настолько фатальной что приложение больше работать не должно? Нужно ли оповестить пользователя об ошибке?

2023-05-22 14:34 UTC, maxlyaptsev commented on internal/app/app.go
> +	Storage  *storage.InMemoryStorage
тут хорошо бы актуализировать название, т.к. стореджа два, будет понятней его специфику добавить

2023-05-24 10:28 UTC, maxlyaptsev requested changes

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/app/apishort.go
> +		log.Println(err)
при получении ошибки мы залогируем ее и продолжим работу. Это точно правильно? Не нужно ли отдать пользователю ошибку?

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/app/apishort.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
ниже не вижу возврата, значит код будет выполняться дальше и статус ответа заменится на 201

2023-05-24 10:28 UTC, maxlyaptsev commented on cmd/shortener/config/config.go
> +	//flag.StringVar(&a.FilePATH, "f", "E:/GoProjects/shortlinks/tmp/short-url-db.json", "It's a FilePATH")
кажется эта строка лишняя

2023-05-24 10:28 UTC, maxlyaptsev commented on cmd/shortener/main.go
>  	flag.Parse()
а почему парсинг флага оказался здесь? У нас есть конфигурация, там устанавливаются значения флагов. Прилжение должно просто готовую структуру с конфигом получить

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/app/apishort_test.go
> +	flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ExitOnError)
а почему падают? Кажется что где-то ошибка, и тест об этом говорит. Лучше выяснить в чем дело, а не подгонять тест. Возможно проблема в том что `flag.Parse()` расположен 

Но вообще не понятен смысл - какие флаги можно получить в юнит тесте? Здесь мы просто запускаем функцию с определенными параметрами и проверяем результат. А флаги используются в командной строке. 

Лучше просто собрать нужный конфиг  - conf := AppConfig{} и передать его в NewApp. Флаги мы все равно прочитать тут никак не можем

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/app/short.go
> +		log.Fatal(err)
в случае ошибки завершим приложение. Оно больше не будет принимать никакие запросы. Его придется перезапускать. Это точно то чего мы ожидаем от хэндлера? Т.е. любой пользователь подобрав запрос с ошибкой сможет положить наш сервис

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/storage/filestorage.go
> +	return err
сюда мы никогда не дойдем - условие выше выкинет панику и завершит приложение

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/storage/filestorage.go
> +		log.Fatal(err)
зачем выкидывать панику и завершать приложение скрыто в пакете? Мы же можем просто вернуть ошибку и дать приложению решить что с этим делать - завершиться или просто залогировать или изменить сторедж на резервный или сделать ретрай. Вариантов много, но здесь мы просто убиваем приложение без каких-либо вариантов

2023-05-24 10:28 UTC, maxlyaptsev commented on internal/app/apishort_test.go
> +func Test_APIGetShortURL(t *testing.T) {
актуально

2023-05-24 17:27 UTC, maxlyaptsev approved these changes

2023-05-24 17:27 UTC, maxlyaptsev commented on internal/storage/filestorage.go
> +		return make(map[string]string)
тут мы просто проигнорировали ошибку - получим пусуой инмемори сторадж и стартанем приложение. А т.к. без этого не будет проверки на дубли - запишем те же ключи что были раньше. При втором старте приложения когда начнем читать файл поймаем дубли, и перезапишем старые ключи новыми урлами. А пользователям потом придется оправдываться что они совсем другое присылали, их просто взломали

2023-05-26 12:07 UTC, merged