Iter20
al-kirpichenko/shortlinks pull request #20
Opened 2023-10-10 13:15 UTC by al-kirpichenko

2023-10-10 21:02 UTC, valentinsoe requested changes
Спасибо за работу!
Из того что надо исправить:
При таком подходе к конфигурации не подключены staticcheck проверки SA*

2023-10-10 21:02 UTC, valentinsoe commented on cmd/staticlint/multichecker.go
> +
Лишняя строка

2023-10-10 21:02 UTC, valentinsoe commented on cmd/staticlint/multichecker.go
> +	for _, v := range staticcheck.Analyzers {
Проверял ли ты, добавляются ли staticcheck анализаторы при такой конфигурации?
На мой взгляд они не добавятся(для теста можешь просто распечатать список анализаторов  mychecks)

2023-10-10 21:02 UTC, valentinsoe commented on internal/myanalizer/myanalizer.go
> +				if isOsExit(x, result) {
Я сидел и думал, может ли быть кейс при котором мы можем найти выражение os.Exit вне определения функции.
И ответ - нет, не может.
Но все равно такой подход к реализации(последовательность кейсов) делает ее не очень очевидной.

2023-10-12 08:02 UTC, al-kirpichenko commented on internal/myanalizer/myanalizer.go
> +				if isOsExit(x, result) {
Я не смог придумать других способов, тема для меня сложная, мне кажется что писать собственные линтеры нужно не раньше, чем года 3 опыта нормальной разработки появится, у меня его нет к сожалению.

2023-10-16 21:18 UTC, valentinsoe commented on internal/myanalizer/myanalizer.go
> +				if isOsExit(x, result) {
Ну кажется как раз есть более линейный и простой спсособ. Просто найдя нужный пакет, начать перебирать его функции, дальше начать перебирать выражения и т.д.

2023-10-16 21:23 UTC, valentinsoe commented on internal/myanalizer/myanalizer.go
> +				if isOsExit(x, result) {
Про наличие опыта. Да, без опыта тема сложная, но на то и "продвинутый" курс.
Ты смог придумать решение, оно хорошее с точки зрения изящества и минимизации кода.
Его минус в том, что оно не тривиальное, и надо потратить время на то, чтобы его понять:)

2023-10-17 02:25 UTC, merged