Iter5
al-kirpichenko/shortlinks pull request #5
Opened 2023-05-05 13:48 UTC by al-kirpichenko

2023-05-05 18:52 UTC, maxlyaptsev requested changes

2023-05-05 18:52 UTC, maxlyaptsev commented on config/config.go
> +	flag.StringVar(&AppConfig.ResultURL, "b", "http://localhost:8080", "It's a Result URL")
конфигурация через env должна быть приоритетной и переписывать значение флага

2023-05-05 18:52 UTC, maxlyaptsev commented on cmd/shortener/main.go
> +	router.Get("/{id}", app.GetOriginalURL)
настройки роутера лучше вынести в отдельный пакет, а в main.go оставить только самые основные вещи  - получение конфигурации и запуск веб-сервера

2023-05-05 18:52 UTC, maxlyaptsev commented on internal/app/short.go
> +	id := r.URL.Path[1:]
у роутера chi есть удобный метод для получения значений из url, его следует использовать. В более сложных настройках с большим количеством параметрво в url, это будет видно более явно - chi сам разбивает строку с адресом и перекладывает значения в контест. Но из-за этого придется немного подкрутить тест и добавить его в контекст т.к. парсинг строки запроса будет происходить на более высоком уровне, тогда как тест будет запускать исключительно handler

2023-05-05 18:52 UTC, maxlyaptsev commented on internal/app/short.go
> +package app
не стоит складывать весь код в один пакет. Сервис который отвечает за генерацию коротких ссылок должен лежать в отдельном пакете, хранение ссылок в пакете для хранения данных (storage/repository),. А хэндлеры в своем пакете. Так происходит разграничение ответственности. Рекомендую почитать про SOLID, хотя go не является ООП языком, но принципы будут полезны и в нем

2023-05-05 18:52 UTC, maxlyaptsev commented on internal/app/short.go
> +func GetShortURL(w http.ResponseWriter, r *http.Request) {
не хватает тестов для ручек. Unit тесты должны тестировать конкретные ручки отдельно от остальной части приложения. Например, если ручки будут лежать в internal/app виде отдельных файлов (в go нормальная практика дробить один пакет на несколько файлов)
- getshort.go
- getoriginal.go

то рядом должны быть тесты 
- getshort_test.go
- getoriginal_test.go

2023-05-05 18:52 UTC, maxlyaptsev commented on internal/app/short.go
> +var urls map[string]string
лучше не не использовать скоуп вне функций без крайней необходимости - лучше создать отдельный пакет, который внутри себя будет хранить мапу, а также добавить в него методы для работы с этим хранилищем

2023-05-05 18:52 UTC, maxlyaptsev commented on internal/app/short.go
> +	urls = make(map[string]string)
получается, что при каждом получении короткой ссылки, будет создваться новая мапа. Что произойдет если нужно будет создать еще одну короткую ссылку?

2023-05-06 04:26 UTC, al-kirpichenko commented on internal/app/short.go
> +	id := r.URL.Path[1:]
подобная конструкция - id := chi.URLParam(r, "id") -  валит автотест тут.. свой я то я могу переписать, но ваш то нет

2023-05-06 04:30 UTC, al-kirpichenko commented on internal/app/short.go
> +func GetShortURL(w http.ResponseWriter, r *http.Request) {
Не понимаю как разнести на 2 отдельных теста: результат, полученный в первом (короткая ссылка) должен быть использован во втором, что затруднительно при использовании 2 самостоятельных файлов

2023-05-06 10:51 UTC, maxlyaptsev requested changes

2023-05-06 10:51 UTC, maxlyaptsev commented on config/config.go
> +var AppConfig struct {
глобальные переменные вещь опасная - изменить значение можно в любой части кода, даже внешние пакеты будут иметь к ней доступ. Лучше явно возвращать значение и явно передавать в методы, где нужна конфигурация

2023-05-06 10:51 UTC, maxlyaptsev commented on internal/app/short.go
> +	id := r.URL.Path[1:]
валится скорее всего именно handler_test т.к. он тоже запускаются во время прогона. Проблему я выше описал - chi берет данные из контекста. Но т.к. тест ручки запускается в изоляции от всего остально, этот контекст не обогощается. Это нужно сделать в тесте самостоятельно. Если с этим трудности - можно в общем чатике написать - думаю все столкнулись с этой проблемой. Разберемся вместе

2023-05-06 10:51 UTC, maxlyaptsev commented on internal/app/short.go
> +func GetShortURL(w http.ResponseWriter, r *http.Request) {
в этом и суть unit тестов - они должны быть независимы. Вот как это можно сделать:

тест получения короткой ссылки
1. создаем хранилище ссылок
2. вызываем ручку для сокращения ссылок
3. проверяем что вернулся результат с короткой ссылкой
4. провреяем что в хранилище ссылка тоже появилась


тест получения полной ссылки
1. создаем хранилище ссылок
2. добавляем в него запись с короткой и длинной ссылкой
3. вызываем ручку получения полной ссылки
4. проверяем что получили редирект на верный адрес (задали в п.2)

2023-05-06 10:51 UTC, maxlyaptsev commented on internal/random/random.go
> +package random
хорошо бы придумать более понятное название, например - shortlinkgenerator, но что-то покороче)
random слишком общее название, которое не дает информации о назначении пакета

2023-05-06 10:51 UTC, maxlyaptsev commented on internal/storage/storage.go
> +var urls = make(map[string]string)
а почему бы не сделать в пакете структуру с полем, которое будет хранить ссылки? У структуры будут методы, которые смогут обращаться к этому полю. Сейчас находится в области видимости всего пакета - это лучше чем глобальная область, но все же это может поломать логику приложения

2023-05-07 21:14 UTC, maxlyaptsev requested changes

2023-05-07 21:14 UTC, maxlyaptsev commented on config/config.go
> +//var AppConfig struct {
в проекте не должно быть закомментированного кода. Если что-то не используется, следует просто удалять

2023-05-07 21:14 UTC, maxlyaptsev commented on internal/storage/storage.go
> +type Storage struct {
решение использовать методы для получения и записи ссыло было хорошее, но мапа должна принадлежать структуре над которой производятся операции, чтобы никакой другой код не имел к нему доступа. 

```go
type Storage struct {
	urls map[string]string
}

func NewStorage() *Storage {
	return &Storage{
		urls: make(map[string]string),
	}
}

func (s *Storage) Set(key, value string) error {
	// code
}

func (s *Storage) Get(key string) (string, bool) {
	// code
}
```

2023-05-08 10:22 UTC, maxlyaptsev approved these changes

2023-05-13 05:16 UTC, merged